# The following overrides should be copied to the core docker-compose.overrides.yml in the main directory.
# Only use them if you DO NOT use the TLS setup.
# If you use the TLS setup, ignore the following values and instead see
# tls/docker-compose.core-override.example.yml for the minio TLS setup values.

services:
  backend:
    environment:
     OPENPROJECT_ATTACHMENTS__STORAGE: "fog"
     OPENPROJECT_FOG_DIRECTORY: "openproject-uploads"
     OPENPROJECT_FOG_CREDENTIALS_PROVIDER: "AWS" # Minio is S3 compliant, so we can use the AWS provider
     OPENPROJECT_FOG_CREDENTIALS_ENDPOINT: "http://127.0.0.1:9000" # URI for your MinIO instance
     OPENPROJECT_FOG_CREDENTIALS_AWS__ACCESS__KEY__ID: "minioadmin"
     OPENPROJECT_FOG_CREDENTIALS_AWS__SECRET__ACCESS__KEY: "minioadmin"
     OPENPROJECT_FOG_CREDENTIALS_PATH__STYLE: "true"
     OPENPROJECT_FOG_CREDENTIALS_REGION: "us-east-1"
     OPENPROJECT_DEV_EXTRA_HOSTS: "${OPENPROJECT_DEV_HOST},http://127.0.0.1:9000"
