# The service defined here overrides the hocuspocus service to use local code for development
# Make sure to adjust the volume path to where your hocuspocus source code is

services:
  hocuspocus:
    # In case of MacOS you need to specify the platform in your `docker/dev/hocuspocus/docker-compose.override.yml`:
    # platform: linux/amd64
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm run dev"
    volumes:
      - ../../../../op-blocknote-hocuspocus:/app
